[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.partitions = default.csv
build_flags = 
    -D CORE_DEBUG_LEVEL=0
lib_deps =
    lovyan03/LovyanGFX @ ^1.1.16
    mathertel/OneButton @ ^2.5.0
    bblanchon/ArduinoJson @ ^6.21.4
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/me-no-dev/AsyncTCP.git
    links2004/WebSockets @ ^2.4.1

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps =
    lovyan03/LovyanGFX @ ^1.1.16
